openapi: 3.0.0
info:
  title: proyek_pos
  version: 1.0.0
servers:
  - url: https://pos-ochre.vercel.app
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: products
  - name: auth
  - name: categories
  - name: transactions
  - name: transaction_items
paths:
  /api/products:
    post:
      tags:
        - products
      summary: post products
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Brownies
                description:
                  type: string
                  example: >-
                    Nikmati kelezatan Brownies Lembut dan Lezat, camilan manis
                    dengan tekstur fudgy di dalam dan sedikit renyah di luar.
                    Dibuat dari bahan berkualitas tinggi seperti cokelat
                    premium, mentega segar, dan gula pilihan, brownies kami
                    menghadirkan rasa yang kaya dan memanjakan setiap gigitan.
                price:
                  type: integer
                  example: '17000'
                stock:
                  type: integer
                  example: '23'
                id_categories:
                  type: string
                  example: fcbd05c7-07fb-4165-9b2e-087517f1189a
                picture:
                  type: string
                  format: binary
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - products
      summary: get products
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/products/{id}:
    get:
      tags:
        - products
      summary: get products by id
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - products
      summary: put products
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
                price:
                  type: string
                stock:
                  type: string
                id_categories:
                  type: string
                  format: binary
                picture:
                  type: string
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - products
      summary: delete products
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/login:
    post:
      tags:
        - auth
      summary: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: fulandihudza@gmail.com
                password: Uca1919
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/auth/register:
    post:
      tags:
        - auth
      summary: register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: uca test
                email: uca@example.com
                password: '123456'
                phone_number: '689876543219'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/categories:
    get:
      tags:
        - categories
      summary: get categories
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - categories
      summary: post categories
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Bakery
                description: Kategori untuk Bakery
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/categories/{id}:
    get:
      tags:
        - categories
      summary: get categories by id
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - categories
      summary: put categories
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Juice
                description: Kategori untuk Minuman Jus
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - categories
      summary: delete categories
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/transactions:
    get:
      tags:
        - transactions
      summary: get transactions
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - transactions
      summary: post transactions
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id_users: 63c1d10b-0347-430a-a9e7-42df0586e817
                total_amount: '182000'
                payment_method: qris
                transaction_date: '2025-02-02T15:55:05.680Z'
                customer_name: Rendy Orthon
                customer_phone: '8357869332'
                table_number: '12'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/transactions/{id}:
    get:
      tags:
        - transactions
      summary: get transactions by id
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - transactions
      summary: put transactions
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id_users: 63c1d10b-0347-430a-a9e7-42df0586e817
                total_amount: '182000'
                payment_method: qris
                transaction_date: '2025-02-02T15:55:05.680Z'
                customer_name: Rendy Orthon
                customer_phone: '8357869332'
                table_number: '12'
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - transactions
      summary: delete transactions
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/transaction-items/{transaction_id}:
    get:
      tags:
        - transaction_items
      summary: get transaction_items by id transactions
      security:
        - bearerAuth: []
      parameters:
        - name: transaction_id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/transaction-items:
    post:
      tags:
        - transaction_items
      summary: post transaction_items
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id_transactions: 38debf18-8fdc-436c-aae1-8d0052d37b78
                id_products: ced48b56-1c28-4628-90c2-eec8369d8187
                quantity: 2
                unit_price: '10000'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/transaction-items/item/{id}:
    get:
      tags:
        - transaction_items
      summary: get transactions_item by id
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

